version: "3"

services:
  web:
    image: nginx:latest
    ports:
      - "5050:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./assets:/usr/share/nginx/html/assets
      - ./pdf:/usr/share/nginx/html/pdf
      - ./images:/usr/share/nginx/html/images
    container_name: portfolio
