version: "3"

services:
  web:
    image: nginx:latest
    ports:
      - "5050:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./:/usr/share/nginx/html/
      
    container_name: portfolio
