name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check SSH Connection
        uses: appleboy/ssh-action@master
        with:
          host: '${{ secrets.HOST }}'
          username: '${{ secrets.USERNAME }}'
          port: '${{ secrets.PORT }}'
          key: "${{ secrets.SSH_KEY }}"
          script: 'echo "SSH connection successful."'

      - name: Check if Docker Container Exists
        id: check-container
        run: |
          if docker ps -a | grep portfolio; then
            echo "Container exists"
            echo "::set-output name=container_exists::true"
          else
            echo "Container does not exist"
            echo "::set-output name=container_exists::false"
          fi

      - name: Deploy via SSH
        uses: tiyee/action-ssh@v1.0.1
        with:
          command: |
            cd /home/docker/stacks/portfolio
            git pull
            if [ "${{ steps.check-container.outputs.container_exists }}" == "true" ]; then
              docker restart portfolio
            else
              docker run -d --name portfolio -p 80:80 your-docker-image:tag
            fi
            host: '${{ secrets.HOST }}'
            username: '${{ secrets.USERNAME }}'
            port: '${{ secrets.PORT }}'
            privateKey: "${{ secrets.SSH_KEY }}
